name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Sync to Glitch
      uses: glitch-tools/sync-glitch-github-action@master
      env:
        GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
        GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
